package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bilhete generated by hbm2java
 */
@Entity
@Table(name = "bilhete", catalog = "cine")
public class Bilhete implements java.io.Serializable {

	private BilheteId id;
	private Usuario usuario;
	private Sessao sessao;
	private String code;

	public Bilhete() {
	}

	public Bilhete(BilheteId id, Usuario usuario, Sessao sessao) {
		this.id = id;
		this.usuario = usuario;
		this.sessao = sessao;
	}

	public Bilhete(BilheteId id, Usuario usuario, Sessao sessao, String code) {
		this.id = id;
		this.usuario = usuario;
		this.sessao = sessao;
		this.code = code;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sessaoid", column = @Column(name = "sessaoid", nullable = false)),
			@AttributeOverride(name = "usuarioid", column = @Column(name = "usuarioid", nullable = false)) })
	public BilheteId getId() {
		return this.id;
	}

	public void setId(BilheteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioid", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sessaoid", nullable = false, insertable = false, updatable = false)
	public Sessao getSessao() {
		return this.sessao;
	}

	public void setSessao(Sessao sessao) {
		this.sessao = sessao;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
