package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BilheteId generated by hbm2java
 */
@Embeddable
public class BilheteId implements java.io.Serializable {

	private int sessaoid;
	private int usuarioid;

	public BilheteId() {
	}

	public BilheteId(int sessaoid, int usuarioid) {
		this.sessaoid = sessaoid;
		this.usuarioid = usuarioid;
	}

	@Column(name = "sessaoid", nullable = false)
	public int getSessaoid() {
		return this.sessaoid;
	}

	public void setSessaoid(int sessaoid) {
		this.sessaoid = sessaoid;
	}

	@Column(name = "usuarioid", nullable = false)
	public int getUsuarioid() {
		return this.usuarioid;
	}

	public void setUsuarioid(int usuarioid) {
		this.usuarioid = usuarioid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BilheteId))
			return false;
		BilheteId castOther = (BilheteId) other;

		return (this.getSessaoid() == castOther.getSessaoid())
				&& (this.getUsuarioid() == castOther.getUsuarioid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSessaoid();
		result = 37 * result + this.getUsuarioid();
		return result;
	}

}
