package br.com.pi.teresina.cine.modelo;
// default package
// Generated 25/05/2014 19:02:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Bilhete generated by hbm2java
 */
@Entity
@Table(name = "bilhete", catalog = "cine")
public class Bilhete implements java.io.Serializable {

	private int sessaoIdsessao;
	private Sessao sessao;
	private Usuario usuario;

	public Bilhete() {
	}

	public Bilhete(Sessao sessao, Usuario usuario) {
		this.sessao = sessao;
		this.usuario = usuario;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sessao"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "sessao_idsessao", unique = true, nullable = false)
	public int getSessaoIdsessao() {
		return this.sessaoIdsessao;
	}

	public void setSessaoIdsessao(int sessaoIdsessao) {
		this.sessaoIdsessao = sessaoIdsessao;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Sessao getSessao() {
		return this.sessao;
	}

	public void setSessao(Sessao sessao) {
		this.sessao = sessao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
