package br.com.pi.teresina.cine.modelo;
// default package
// Generated 25/05/2014 19:02:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cadastro generated by hbm2java
 */
@Entity
@Table(name = "cadastro", catalog = "cine", uniqueConstraints = @UniqueConstraint(columnNames = "cpf_cnpj"))
public class Cadastro implements java.io.Serializable {

	private Integer idcadastro;
	private long cpfCnpj;
	private String descricao;
	private String email;
	private String cep;
	private String contato;
	private Set<Cinema> cinemas = new HashSet<Cinema>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Cadastro() {
	}

	public Cadastro(long cpfCnpj, String descricao, String email) {
		this.cpfCnpj = cpfCnpj;
		this.descricao = descricao;
		this.email = email;
	}

	public Cadastro(long cpfCnpj, String descricao, String email, String cep,
			String contato, Set<Cinema> cinemas, Set<Usuario> usuarios) {
		this.cpfCnpj = cpfCnpj;
		this.descricao = descricao;
		this.email = email;
		this.cep = cep;
		this.contato = contato;
		this.cinemas = cinemas;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcadastro", unique = true, nullable = false)
	public Integer getIdcadastro() {
		return this.idcadastro;
	}

	public void setIdcadastro(Integer idcadastro) {
		this.idcadastro = idcadastro;
	}

	@Column(name = "cpf_cnpj", unique = true, nullable = false)
	public long getCpfCnpj() {
		return this.cpfCnpj;
	}

	public void setCpfCnpj(long cpfCnpj) {
		this.cpfCnpj = cpfCnpj;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cep", length = 45)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "contato", length = 45)
	public String getContato() {
		return this.contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadastro")
	public Set<Cinema> getCinemas() {
		return this.cinemas;
	}

	public void setCinemas(Set<Cinema> cinemas) {
		this.cinemas = cinemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadastro")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
