package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cadastrocinema generated by hbm2java
 */
@Entity
@Table(name = "cadastrocinema", catalog = "cine", uniqueConstraints = {
		@UniqueConstraint(columnNames = "razaosocial"),
		@UniqueConstraint(columnNames = "cnpj"),
		@UniqueConstraint(columnNames = "email") })
public class Cadastrocinema implements java.io.Serializable {

	private int id;
	private Cinema cinema;
	private long cnpj;
	private String razaosocial;
	private String email;

	public Cadastrocinema() {
	}

	public Cadastrocinema(Cinema cinema, long cnpj, String razaosocial,
			String email) {
		this.cinema = cinema;
		this.cnpj = cnpj;
		this.razaosocial = razaosocial;
		this.email = email;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "cinema"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "cnpj", unique = true, nullable = false)
	public long getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(long cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "razaosocial", unique = true, nullable = false, length = 50)
	public String getRazaosocial() {
		return this.razaosocial;
	}

	public void setRazaosocial(String razaosocial) {
		this.razaosocial = razaosocial;
	}

	@Column(name = "email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
