package br.com.pi.teresina.cine.modelo;
// default package
// Generated 25/05/2014 19:02:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cinema generated by hbm2java
 */
@Entity
@Table(name = "cinema", catalog = "cine")
public class Cinema implements java.io.Serializable {

	private Integer idcinema;
	private Cadastro cadastro;
	private Set<Filme> filmes = new HashSet<Filme>(0);

	public Cinema() {
	}

	public Cinema(Cadastro cadastro) {
		this.cadastro = cadastro;
	}

	public Cinema(Cadastro cadastro, Set<Filme> filmes) {
		this.cadastro = cadastro;
		this.filmes = filmes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcinema", unique = true, nullable = false)
	public Integer getIdcinema() {
		return this.idcinema;
	}

	public void setIdcinema(Integer idcinema) {
		this.idcinema = idcinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcadastro", nullable = false)
	public Cadastro getCadastro() {
		return this.cadastro;
	}

	public void setCadastro(Cadastro cadastro) {
		this.cadastro = cadastro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cinema")
	public Set<Filme> getFilmes() {
		return this.filmes;
	}

	public void setFilmes(Set<Filme> filmes) {
		this.filmes = filmes;
	}

}
