package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ControleAcesso generated by hbm2java
 */
@Entity
@Table(name = "controle_acesso", catalog = "cine")
public class ControleAcesso implements java.io.Serializable {

	private int id;
	private String perfil;

	public ControleAcesso() {
	}

	public ControleAcesso(int id, String perfil) {
		this.id = id;
		this.perfil = perfil;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "perfil", nullable = false, length = 45)
	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

}
