package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Extras generated by hbm2java
 */
@Entity
@Table(name = "extras", catalog = "cine")
public class Extras implements java.io.Serializable {

	private int usuarioid;
	private Usuario usuario;
	private String descricao;
	private BigDecimal valor;

	public Extras() {
	}

	public Extras(Usuario usuario, String descricao) {
		this.usuario = usuario;
		this.descricao = descricao;
	}

	public Extras(Usuario usuario, String descricao, BigDecimal valor) {
		this.usuario = usuario;
		this.descricao = descricao;
		this.valor = valor;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "usuarioid", unique = true, nullable = false)
	public int getUsuarioid() {
		return this.usuarioid;
	}

	public void setUsuarioid(int usuarioid) {
		this.usuarioid = usuarioid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", precision = 6)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
