package br.com.pi.teresina.cine.modelo;
// default package
// Generated 25/05/2014 19:02:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Filme generated by hbm2java
 */
@Entity
@Table(name = "filme", catalog = "cine", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Filme implements java.io.Serializable {

	private Integer idfilme;
	private Cinema cinema;
	private String descricao;
	private Set<Sessao> sessaos = new HashSet<Sessao>(0);

	public Filme() {
	}

	public Filme(Cinema cinema, String descricao) {
		this.cinema = cinema;
		this.descricao = descricao;
	}

	public Filme(Cinema cinema, String descricao, Set<Sessao> sessaos) {
		this.cinema = cinema;
		this.descricao = descricao;
		this.sessaos = sessaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idfilme", unique = true, nullable = false)
	public Integer getIdfilme() {
		return this.idfilme;
	}

	public void setIdfilme(Integer idfilme) {
		this.idfilme = idfilme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_idcinema", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "descricao", unique = true, nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filme")
	public Set<Sessao> getSessaos() {
		return this.sessaos;
	}

	public void setSessaos(Set<Sessao> sessaos) {
		this.sessaos = sessaos;
	}

}
