package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filme generated by hbm2java
 */
@Entity
@Table(name = "filme", catalog = "cine")
public class Filme implements java.io.Serializable {

	private Integer id;
	private Cinema cinema;
	private String descricao;
	private Set sessaos = new HashSet(0);

	public Filme() {
	}

	public Filme(Cinema cinema, String descricao) {
		this.cinema = cinema;
		this.descricao = descricao;
	}

	public Filme(Cinema cinema, String descricao, Set sessaos) {
		this.cinema = cinema;
		this.descricao = descricao;
		this.sessaos = sessaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinemaid", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filme")
	public Set getSessaos() {
		return this.sessaos;
	}

	public void setSessaos(Set sessaos) {
		this.sessaos = sessaos;
	}

}
