package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sessao generated by hbm2java
 */
@Entity
@Table(name = "sessao", catalog = "cine")
public class Sessao implements java.io.Serializable {

	private int id;
	private Filme filme;
	private Date dataSessao;
	private BigDecimal valor;
	private Date duracaoSessao;
	private String descricao;
	private Integer lugares;
	private Set bilhetes = new HashSet(0);

	public Sessao() {
	}

	public Sessao(int id, Filme filme, Date dataSessao, BigDecimal valor) {
		this.id = id;
		this.filme = filme;
		this.dataSessao = dataSessao;
		this.valor = valor;
	}

	public Sessao(int id, Filme filme, Date dataSessao, BigDecimal valor,
			Date duracaoSessao, String descricao, Integer lugares, Set bilhetes) {
		this.id = id;
		this.filme = filme;
		this.dataSessao = dataSessao;
		this.valor = valor;
		this.duracaoSessao = duracaoSessao;
		this.descricao = descricao;
		this.lugares = lugares;
		this.bilhetes = bilhetes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filmeid", nullable = false)
	public Filme getFilme() {
		return this.filme;
	}

	public void setFilme(Filme filme) {
		this.filme = filme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_sessao", nullable = false, length = 19)
	public Date getDataSessao() {
		return this.dataSessao;
	}

	public void setDataSessao(Date dataSessao) {
		this.dataSessao = dataSessao;
	}

	@Column(name = "valor", nullable = false, precision = 6)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "duracao_sessao", length = 8)
	public Date getDuracaoSessao() {
		return this.duracaoSessao;
	}

	public void setDuracaoSessao(Date duracaoSessao) {
		this.duracaoSessao = duracaoSessao;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "lugares")
	public Integer getLugares() {
		return this.lugares;
	}

	public void setLugares(Integer lugares) {
		this.lugares = lugares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sessao")
	public Set getBilhetes() {
		return this.bilhetes;
	}

	public void setBilhetes(Set bilhetes) {
		this.bilhetes = bilhetes;
	}

}
