package br.com.pi.teresina.cine.modelo;
// default package
// Generated 25/05/2014 19:02:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sessao generated by hbm2java
 */
@Entity
@Table(name = "sessao", catalog = "cine")
public class Sessao implements java.io.Serializable {

	private Integer idsessao;
	private Filme filme;
	private String descricao;
	private Date dataSessao;
	private Date duracaoSessao;
	private Integer lugares;
	private Bilhete bilhete;

	public Sessao() {
	}

	public Sessao(Filme filme, Date dataSessao, Date duracaoSessao) {
		this.filme = filme;
		this.dataSessao = dataSessao;
		this.duracaoSessao = duracaoSessao;
	}

	public Sessao(Filme filme, String descricao, Date dataSessao,
			Date duracaoSessao, Integer lugares, Bilhete bilhete) {
		this.filme = filme;
		this.descricao = descricao;
		this.dataSessao = dataSessao;
		this.duracaoSessao = duracaoSessao;
		this.lugares = lugares;
		this.bilhete = bilhete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idsessao", unique = true, nullable = false)
	public Integer getIdsessao() {
		return this.idsessao;
	}

	public void setIdsessao(Integer idsessao) {
		this.idsessao = idsessao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfilme", nullable = false)
	public Filme getFilme() {
		return this.filme;
	}

	public void setFilme(Filme filme) {
		this.filme = filme;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_sessao", nullable = false, length = 19)
	public Date getDataSessao() {
		return this.dataSessao;
	}

	public void setDataSessao(Date dataSessao) {
		this.dataSessao = dataSessao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "duracao_sessao", nullable = false, length = 8)
	public Date getDuracaoSessao() {
		return this.duracaoSessao;
	}

	public void setDuracaoSessao(Date duracaoSessao) {
		this.duracaoSessao = duracaoSessao;
	}

	@Column(name = "lugares")
	public Integer getLugares() {
		return this.lugares;
	}

	public void setLugares(Integer lugares) {
		this.lugares = lugares;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sessao")
	public Bilhete getBilhete() {
		return this.bilhete;
	}

	public void setBilhete(Bilhete bilhete) {
		this.bilhete = bilhete;
	}

}
