package br.com.pi.teresina.cine.modelo;

// Generated 26/05/2014 22:06:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "cine", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String login;
	private String senha;
	private Cadastrousuario cadastrousuario;
	private Extras extras;
	private Set bilhetes = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String login, String senha) {
		this.login = login;
		this.senha = senha;
	}

	public Usuario(String login, String senha, Cadastrousuario cadastrousuario,
			Extras extras, Set bilhetes) {
		this.login = login;
		this.senha = senha;
		this.cadastrousuario = cadastrousuario;
		this.extras = extras;
		this.bilhetes = bilhetes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", unique = true, nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", nullable = false)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Cadastrousuario getCadastrousuario() {
		return this.cadastrousuario;
	}

	public void setCadastrousuario(Cadastrousuario cadastrousuario) {
		this.cadastrousuario = cadastrousuario;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Extras getExtras() {
		return this.extras;
	}

	public void setExtras(Extras extras) {
		this.extras = extras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set getBilhetes() {
		return this.bilhetes;
	}

	public void setBilhetes(Set bilhetes) {
		this.bilhetes = bilhetes;
	}

}
